name: Release on Pypi

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pypa
      run: >-
        pip install hatch
    - name: Install
      uses: pandoc/actions/setup@main
    - name: Pulish
      run: |
        make build
        hatch publish -u '__token__' -a '${{ secrets.HATCH_INDEX_AUTH }}'
